---
title: "Repeated_holout_WQS"
author: "Yanelli Nunez"
date: "12/9/2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth : 4
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)


library(tidyverse)
library(broom)

library(gWQS)

options(scipen = 999)
```


```{r}
sessionInfo()
```

## Data Import and Cleaning

```{r import}
# import the dataset
dataset = read_csv(here::here("Data/studypop.csv"))

# define the chemicals to include in the mixture
mixture = c("LBX074LA", "LBX099LA", "LBX118LA", "LBX138LA", "LBX153LA", "LBX170LA", "LBX180LA", "LBX187LA",
            "LBX194LA", "LBXD03LA", "LBXD05LA", "LBXD07LA", "LBXF03LA", "LBXF04LA", "LBXF05LA", "LBXF08LA",
            "LBXHXCLA", "LBXPCBLA")

# log-transform the outcome
dataset$log_TELOMEAN = log(dataset$TELOMEAN)
dataset$valid.var <- c(sample(c(0,1), dim(dataset)[1], replace=TRUE))



# redefine variables race_cat and edu_cat as factors
dataset$race_cat = factor(dataset$race_cat, levels = c(1, 2, 3, 4), labels = c(1, 2, 3, 4))
dataset$edu_cat = factor(dataset$edu_cat, levels = c(1, 2, 3, 4), labels = c(1, 2, 3, 4))
dataset$bmi_cat3 = factor(dataset$bmi_cat3, levels = c(1, 2, 3), labels = c(1, 2, 3))
```


### Positive Adjusted Model


```{r code for new package}
# adjust for covariates:
# blood data: LBXWBCSI LBXLYPCT LBXMOPCT LBXEOPCT LBXBAPCT LBXNEPCT
# demographics: age_cent age_sq race_cat bmi_cat3 ln_lbxcot edu_cat


gwqs_new = gwqs(log_TELOMEAN ~ wqs + LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat + male, 
               mix_name = mixture, data = dataset, q = 10, 
               validation = 0.6, b = 100, b1_pos = TRUE, b1_constr = FALSE, 
               family = "gaussian", 
               seed = 123, plots = TRUE, tables = TRUE)


df <- tidy(gwqs_new$fit) #use "tidy" from the broom package to easily create a dataframe!
gwqs_new$fit #includes the coefficients for the covariants and the mixture "index"
gwqs_new$final_weights %>% knitr::kable()
```


#This bootstraps the single-partition WQS 100 times to create a distribution of validated results

```{r}

seed = 8989 

rep_hold_no_seed = lapply(1:100, function(i) {
  gwqs_new = gwqs(log_TELOMEAN ~ wqs + LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat + male, 
               mix_name = mixture,
               data = dataset, 
               q = 10, 
               validation = 0.6, 
               b = 10, # 100 bootstraps recommended, but gWQS runs faster with fewer
               b1_pos = TRUE, b1_constr = FALSE, 
               family = "gaussian", 
              plots = F, tables = F)})
```


# Function to compile results from 100 repeated holdouts
```{r}
f_compile <- function(gWQSresult){ # gWQSresult = gWQS results name for repeated holdout (a list)

  # WQS index beta estimates
  tmp1 = map(gWQSresult,"fit") %>% map(tidy) # convert fit results to a dataframe; you need the package "broom" to be able to use map(tidy) combo
  tmp1 = map2(tmp1,1:length(tmp1),function(x,y){x$rep=y; return(x)}) # add repetition index number
  tmp1 = do.call("rbind",tmp1) # bind all repetitions together
  tmp1 = subset(tmp1, term=="wqs") # subset results to just the wqs-index estimate
  
  # Chemical weights
  tmp3 = map(gWQSresult,"final_weights") # convert weight results to a dataframe
  tmp3 = map2(tmp3,1:length(tmp3),function(x,y){x$rep.rep=y; return(x)}) # add repetition index number
  tmp3 = do.call("rbind",tmp3) # bind all repetitions together
  tmp3 = reshape(tmp3, timevar="mix_name", idvar="rep.rep", direction="wide") # put weights in wide format
  names(tmp3) = sub(".*\\.", "", names(tmp3)) # remove 'mean_weight.' 
  
  # Merge estimates & weights
  tmp4 = merge(tmp1,tmp3,by="rep") 
  tmp4 <- subset(tmp4, select=-c(term,statistic,std.error,p.value)) # drop unecessary variables
}

# Apply f_compile function to put repeated holdout results into dataframe
rep.hold.df = f_compile(rep_hold)
rep.hold.df.2 = f_compile(rep_hold_no_seed)
```




```{r}
# Check the WQS index estimate distribution - if not approximately ~N then more repetitions needed
hist(rep.hold.df.2$estimate)

# Calculate the nonparametric WQS index estimate & 95% CI from repeated holdout sampling distributon
median(rep.hold.df.2$estimate) 
quantile(rep.hold.df.2$estimate,0.025) 
quantile(rep.hold.df.2$estimate,0.975)
## How does this estimate compare to the single and no partition methods?

# Calculate mean weights
colMeans(rep.hold.df.2[,3:12])
```




```{r function code, cache = TRUE}

rep_hold_no_seed = lapply(1:100, function(i) {
  gwqs_new = gwqs(log_TELOMEAN ~ wqs + LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat + male, 
               mix_name = mixture,
               data = dataset, 
               q = 10, 
               validation = 0.6, 
               b = 10, # 100 bootstraps recommended, but gWQS runs faster with fewer
               b1_pos = TRUE, b1_constr = FALSE, 
               family = "gaussian", 
              plots = F, tables = F)})



fit_gwqs_new = function(seed) {
  gwqs = gwqs(log_TELOMEAN ~ wqs + LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + 
               age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat + male, 
               mix_name = mixture, 
              data = dataset, 
              q = 10, 
               validation = 0.6,
              b = 100, 
              b1_pos = TRUE, b1_constr = FALSE, 
              family = "gaussian", 
              seed = seed, 
              plots = FALSE, tables = FALSE)


weights <- as_tibble(gwqs$final_weights, rownames = "variable") %>% 
    select(-mix_name) 
  weights

}


seed_num = 1:50 
repeat_gwqs_new = 
  tibble(seed = seed_num) %>% 
  mutate(
    fits = map(seed, ~fit_gwqs_new(seed = .x))) %>%
  unnest() 


```

Plotting the results 
```{r plot}
repeat_gwqs_new %>%
  ggplot() + 
  geom_point(aes(x = seed, y = mean_weight), color = "red", size = 0.5, alpha = 0.5) + 
  facet_wrap(~variable) + 
  geom_hline(yintercept = 0) +
  ggtitle("R3.6.1 & gWQS 2.0") 
 # theme(axis.text.x = element_text(angle = 90, size = 4))
```


